dist: trusty
services:
  - docker
before_script:
  - docker pull drugilsberg/rdkit-ubuntu:latest
  - docker build -f .travis/Dockerfile -t paccmann_polymer .
script:
  - docker run -it paccmann_polymer python3 -c "import paccmann_polymer"
  - docker run -it paccmann_polymer python3 -m unittest discover -t . -p "test_*py" paccmann_polymer
  - docker run -it paccmann_polymer python3 -m mypy --ignore-missing-imports paccmann_polymer

